import type { InformationCard } from "@/lib/content/schema";

export const sampleCards: InformationCard[] = [
  {
    slug: "campus-card-lost",
    title: "校园卡丢了怎么办",
    category: "新生",
    tags: ["校园卡", "补办", "挂失", "一卡通"],
    audience: "校园卡丢失或疑似被盗刷的同学",
    conclusion: "先挂失，确认余额和实体卡状态后，再按服务点要求补办。",
    steps: ["打开校园卡或一卡通服务入口完成挂失", "确认是否仍需要补办实体卡", "带身份证件到服务点按现场要求补办"],
    notes: ["补卡费用、窗口时间和地点可能变化，以现场或官方入口为准。", "如果怀疑被盗刷，保留消费记录截图。"],
    sourceType: "官方来源",
    sourceUrl: "https://net.ncu.edu.cn/info/1025/4779.htm",
    updatedAt: "2026-04-26",
    trustStatus: "官方来源",
    reviewStatus: "published",
    riskLevel: "medium",
    relatedCards: ["校园卡充值", "常用电话与服务入口"],
  },
  {
    slug: "network-connect",
    title: "校园网连不上怎么办",
    category: "生活",
    tags: ["校园网", "网络", "宿舍网络", "认证", "报修"],
    audience: "无法连接 NCUWLAN、宿舍网络或认证失败的同学",
    conclusion: "先确认网络区域和认证状态，再通过官方报修入口提交问题。",
    steps: ["确认当前区域使用的校园网名称", "重新打开认证页面并检查账号密码", "仍无法连接时提交网络报修"],
    notes: ["宿舍区和教学办公区网络名称可能不同。", "运营商套餐、资费和合约不在本卡片内给确定结论。"],
    sourceType: "官方来源",
    sourceUrl: "https://xxwl.ncu.edu.cn/info/1010/6179.htm",
    updatedAt: "2026-04-26",
    trustStatus: "官方来源",
    reviewStatus: "published",
    riskLevel: "medium",
    relatedCards: ["常用电话与服务入口"],
  },
  {
    slug: "dorm-repair",
    title: "宿舍报修怎么走",
    category: "生活",
    tags: ["宿舍", "报修", "后勤", "水电", "维修"],
    audience: "宿舍设施、水电、门窗等需要报修的同学",
    conclusion: "优先走后勤线上报修；紧急问题直接联系后勤服务热线。",
    steps: ["进入后勤报修入口", "填写宿舍楼栋、房间和问题照片", "等待维修人员联系或查看处理进度"],
    notes: ["假期和特殊时段的服务安排可能变化。", "涉及安全隐患时不要只等线上反馈。"],
    sourceType: "官方来源",
    sourceUrl: "https://hqbzc.ncu.edu.cn/glyfw/fwzn/373f4b9832c1482d97d60bcf166bb83d.htm",
    updatedAt: "2026-04-26",
    trustStatus: "官方来源",
    reviewStatus: "published",
    riskLevel: "medium",
    relatedCards: ["常用电话与服务入口"],
  },
  {
    slug: "canteen-guide",
    title: "食堂吃饭怎么选",
    category: "生活",
    tags: ["食堂", "吃饭", "餐厅", "新生"],
    audience: "刚到校、想快速找到吃饭选择的同学",
    conclusion: "先按上课区域和宿舍位置选最近食堂，再逐步试常去窗口。",
    steps: ["看当天上课或宿舍位置", "优先选择步行最近的食堂", "错峰尝试不同窗口并记录适合自己的口味"],
    notes: ["口味体验来自同学经验，窗口营业状态会变化。", "食品安全或权益问题应走学校反馈渠道。"],
    sourceType: "同学经验",
    sourceUrl: "",
    updatedAt: "2026-04-26",
    trustStatus: "同学经验已核实",
    reviewStatus: "published",
    riskLevel: "low",
    relatedCards: ["常用电话与服务入口"],
  },
  {
    slug: "phone-directory",
    title: "常用电话与服务入口",
    category: "生活",
    tags: ["电话", "服务入口", "保卫处", "后勤", "医保", "咨询"],
    audience: "需要快速找到校内服务入口或咨询电话的同学",
    conclusion: "先打开公共服务入口，再按事项联系对应部门。",
    steps: ["确认问题属于后勤、网络、保卫、医保还是教务", "打开学校公共服务或对应部门入口", "保存通话记录或咨询截图以便后续处理"],
    notes: ["电话、地点和服务时间变化较快，拨打前最好核对最新入口。"],
    sourceType: "官方来源",
    sourceUrl: "https://www.ncu.edu.cn/index/ggfw.htm",
    updatedAt: "2026-04-26",
    trustStatus: "官方来源",
    reviewStatus: "published",
    riskLevel: "medium",
    relatedCards: ["宿舍报修怎么走", "校园网连不上怎么办"],
  },
  {
    slug: "campus-transport",
    title: "校内交通怎么安排",
    category: "新生",
    tags: ["交通", "校车", "通勤", "前湖校区"],
    audience: "不熟悉校内路线和通勤时间的同学",
    conclusion: "先按宿舍、教学楼和当天时间规划路线，重要事项提前出门。",
    steps: ["确认目的地楼栋", "预留步行和等车时间", "第一次去新地点时提前 15 分钟出发"],
    notes: ["车辆班次和路线可能调整，临时安排以现场和官方通知为准。"],
    sourceType: "同学经验",
    sourceUrl: "",
    updatedAt: "2026-04-26",
    trustStatus: "待核实",
    reviewStatus: "published",
    riskLevel: "low",
    relatedCards: ["常用电话与服务入口"],
  },
];
