import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually define sidebar to control order and add emojis
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: '📝 写在前面',
    },
    {
      type: 'category',
      label: '📚 课程',
      link: {
        type: 'doc',
        id: 'courses/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'courses',
        },
      ],
    },
    {
      type: 'category',
      label: '📒 黄页',
      link: {
        type: 'doc',
        id: 'yellow-pages/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'yellow-pages',
        },
      ],
    },
    {
      type: 'category',
      label: '🎓 学习',
      link: {
        type: 'doc',
        id: 'study/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'study',
        },
      ],
    },
    {
      type: 'category',
      label: '🏠 生活',
      link: {
        type: 'doc',
        id: 'life/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'life',
        },
      ],
    },
    {
      type: 'category',
      label: '💼 经验包',
      link: {
        type: 'doc',
        id: 'experience/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'experience',
        },
      ],
    },
    {
      type: 'category',
      label: '👥 贡献者',
      link: {
        type: 'doc',
        id: 'contributors/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'contributors',
        },
      ],
    },
  ],
};

export default sidebars;
